appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ur0aMxL4CExU4ikZH6WgOwQCOSgh46YLp8ZSS6JacgprNWZpU1A8m2clBV/kS8jbcJTlUIRlZw8y41Y+y1SyC4foGiKLX1Ab1bZBwr1UDP8L5oeYwcsS/fEnMQyjga/m/34Kl8xaYnnSnEMYh3PdqRvAILqBEhYPQWg32Ko6rnK5Q4YhDpG2YupTI3kYV25vyZg7Gjuo9iYkUo5elwacHyaRhp/VTOi878aa29G22YfPje4dy8kN0PoAf9k1KfCVYCfZ77WU07sYOudQmFk4vfNHTEaR+ODjvD3NuwuThnn8ANPEc2CQKb8qIoLGZjUevxijLoz70fCvrTNJPA+7Dqg9SftjfbMxaa8g7RcvYaSmO3UFDtWvzMVqn9DwN35Zp4gUX8l1ruebC/MclMsaEmfYEPSWnEGaGzufis/k1F0mb36NS8QcC55smfam9jjO3hKQh7yIL9ZJOJh6W2yJonrj8PaUC55LvAL28L2n9fLn1R6EXJG6o+iyzpukMYpJukAhqreyzWa2sXtTgI5/DcuJXUwkCwNvUFP0RE6gh7kMBhRS367ejNr9cCpkjXuxAY3XpZFjuHl6yDfRCHlJL16y1FG2AZbfa19aFMiJpmTtasDGyIIh/MrOJCi0Gbq4RbAV+MUlOIGr92KYP8dK9Lz45uJiAMjJ9Py0yCGG5Wc=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
